version: "3.9"
services:
  limesurvey:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${LIMESURVEY_CONTAINER_NAME:-limesurvey}
    restart: always
    environment:
      LIMESURVEY_DOMAIN: ${LIMESURVEY_DOMAIN}
      LIMESURVEY_ADMIN_EMAIL: ${LIMESURVEY_ADMIN_EMAIL}
    volumes:
      - ${LIMESURVEY_DIR}/tmp:/var/www/html/tmp
      - ${LIMESURVEY_DIR}/upload:/var/www/html/upload
      - ${LIMESURVEY_DIR}/application/config:/var/www/html/application/config
    expose:
      - ${LIMESURVEY_PORT:-80}:80
  postgres:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB:-limesurvey_db}
      POSTGRES_USER: ${POSTGRES_USER:-limesurvey}
    volumes:
      - ${LIMESURVEY_DB_DATA}:/var/lib/postgresql/data
